import {
  Sprout, Beef, Fish, ShoppingBag, Hammer, Car, GraduationCap,
  Stethoscope, Building2, HardHat, Wrench, UtensilsCrossed,
  Scissors, Zap, Droplets, Shield, Banknote, Radio, Newspaper,
  BookOpen, Home, Sunset, Globe, LucideIcon,
  Pill, Baby, Brain, Microscope, Scale, Calculator, Camera, Dumbbell,
  ChefHat, Leaf, Package, TrendingUp, ArrowLeftRight,
  Palette, Hotel, Languages, School, Flame, Snowflake, PaintBucket,
  Layers, HeartHandshake, Syringe, Building,
  HeartPulse, Cross, Dog, Eye, Presentation, Landmark, Umbrella, Gavel,
  Cpu, Code, PencilRuler, Megaphone, Siren, Wheat, Brush, Trophy, Cog,
  Trees, Moon, Drill
} from 'lucide-react'

// Noms interdits — aucun groupe ne peut être créé avec ces termes
export const BLOCKED_ACTIVITY_TERMS = [
  'musique', 'chanteur', 'chanteuse', 'danseur', 'danseuse',
  'artiste', 'prostitué', 'prostituée', 'escort',
]

export function isActivityBlocked(name: string): boolean {
  const lower = name.toLowerCase()
  return BLOCKED_ACTIVITY_TERMS.some(term => lower.includes(term))
}

// Mapping activité → icône Lucide — chaque activité a son propre logo distinct,
// jamais partagé avec une autre, pour qu'on les reconnaisse au premier coup d'œil.
export const ACTIVITY_ICONS: Record<string, LucideIcon> = {
  'Santé':                    Stethoscope,
  'Médecin':                  HeartPulse,
  'Infirmier/Infirmière':     Syringe,
  'Pharmacien':               Pill,
  'Sage-femme':               Baby,
  'Dentiste':                 Cross,
  'Psychologue/Thérapeute':   Brain,
  'Kiné/Physiothérapeute':    Dumbbell,
  'Vétérinaire':              Dog,
  'Opticien':                 Eye,
  'Élève':                    School,
  'Étudiant':                 BookOpen,
  'Enseignement':             GraduationCap,
  'Professeur/Formateur':     Presentation,
  'Chercheur/Scientifique':   Microscope,
  'Administration':           Landmark,
  'Avocat/Juriste':           Scale,
  'Comptable/Auditeur':       Calculator,
  'Économiste':               TrendingUp,
  'Banque/Finance':           Banknote,
  'Assurance':                Umbrella,
  'Agent immobilier':         Building,
  'Notaire/Huissier':         Gavel,
  'Informatique':             Cpu,
  'Développeur/Programmeur':  Code,
  'Graphiste/Designer':       Palette,
  'Cybersécurité':            Shield,
  'Télécommunications':       Radio,
  'Construction':             HardHat,
  'Maçonnerie':               Drill,
  'Menuiserie':               Hammer,
  'Électricité':              Zap,
  'Plomberie':                Droplets,
  'Soudure/Métallurgie':      Flame,
  'Climatisation/Froid':      Snowflake,
  'Peinture en bâtiment':     PaintBucket,
  'Carrelage':                Layers,
  'Mécanique':                Wrench,
  'Artisanat':                PencilRuler,
  'Couture':                  Scissors,
  'Commerce':                 ShoppingBag,
  'Import/Export':            ArrowLeftRight,
  'Marketing/Communication':  Megaphone,
  'Transport':                Car,
  'Logistique':               Package,
  'Journalisme':              Newspaper,
  'Sécurité':                 Siren,
  'Agriculture':              Sprout,
  'Maraîchage':               Leaf,
  'Élevage':                  Beef,
  'Pêche':                    Fish,
  'Boulangerie/Pâtisserie':   ChefHat,
  'Restauration':             UtensilsCrossed,
  'Agroalimentaire':          Wheat,
  'Coiffure':                 Brush,
  'Hôtellerie/Tourisme':      Hotel,
  'Photographie/Vidéo':       Camera,
  'Sport/Coach sportif':      Trophy,
  'Ingénierie':               Cog,
  'Architecture':             Building2,
  'Environnement/Écologie':   Trees,
  'Travail social':           HeartHandshake,
  'Imam/Prédicateur':         Moon,
  'Traducteur/Interprète':    Languages,
  'Sans emploi':              Home,
  'Retraité':                 Sunset,
  'Autre':                    Globe,
}
